### ISSUE TITLE
Merge, Revert 커밋은 Commitlint 적용이 안 될까?

### ISSUE THREAD

**Issue by Eu4ng** [Eu4ng/commitlint-github#5]
## 참고

- [How to lint the message of a pull request merge commit?](https://stackoverflow.com/questions/74352636/how-to-lint-the-message-of-a-pull-request-merge-commit)
- [GitLab Server-Side Hook 을 통해 Commit Message Convention 강제하기](https://anencore94.github.io/2020/08/21/gitlab-server-hook.html)

## 알아낸 것

1. `Require linear history` 옵션을 사용하면 Merge Commit 자체를 막을 수는 있다.
    ![image](https://github.com/Eu4ng/test-commitlint/assets/59055049/9d694aa3-22c1-4cf1-a360-3263fd6878b6)
2. `GitHub Enterprise Server` 나 `GitLab` 의 pre-receive-hook 을 사용하여 서버 hook 을 이용하는 것이 좋다.
    ![image](https://github.com/Eu4ng/test-commitlint/assets/59055049/1d15bc4f-bab4-40b2-9337-5da6fadc90bc)

**Comment by Eu4ng** [comment]
## 참고

[Running your pull_request workflow when a pull request merges](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-pull_request-workflow-when-a-pull-request-merges)

PR 이 병합된 이후 호출하는 방법
```yaml
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
```
